### ISSUE TITLE
Error: No product reader found for zip

### ISSUE THREAD

**Issue by albhasan** [asfadmin/grfn-s1tbx-rtc#61]
Good morning, 

I'm running an Ubuntu 14.04.5 LTS and I ran the following command:

`
sh s1tbx-rtc.sh --granule S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B
`

Then, I get the following message:

`
Error: No product reader found for '/work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip'
`

The complete output is

`
sudo sh s1tbx-rtc.sh --granule S1B_IW_GRDH_1SDV_20190430T161529
_20190430T161554_016038_01E295_771B
[sudo] password for XXXXXXXXXX: 
latest: Pulling from asfdaac/s1tbx-rtc
3b2f3b841c08: Already exists 
d9473fe79ae2: Already exists 
12ca40da59aa: Already exists 
371e12fec7fb: Already exists 
6e9976d42f51: Already exists 
2beda3cb9098: Already exists 
52fe513248dd: Already exists 
17ede1f74374: Already exists 
4b9adb1fe10f: Already exists 
e06442164f22: Already exists 
7484b8cfcdd8: Already exists 
3d39e17b30ea: Already exists 
9ed2b964466a: Already exists 
5f1e03cf3d87: Already exists 
1d0547589f6a: Already exists 
9d4ee1a28d5c: Already exists 
Digest: sha256:b856a2bb790084d833335688cc4e1a4b55675c44f3c3934867e664f677802c7a
Status: Image is up to date for asfdaac/s1tbx-rtc:latest

Earthdata Login username: XXXXXXXXXXXX@XXXXXXXXX.XX

Earthdata Login password: 

Fetching granule information

Downloading granule from https://datapool.asf.alaska.edu/GRD_HD/SB/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip

Preparing digital elevation model
Snapping to grid at posting of 30 meters
Total ned13 4.251283331218865 5.153048980215999 0.8250034780458587
Total srtmgl1 4.244142131781835 5.153048980215999 0.8236176578325353
Total srtmau1 0 5.153048980215999 0.0
Total ned1 4.270356053122839 5.153048980215999 0.828704727922815
Total ned2 0 5.153048980215999 0.0
Total srtmgl3 4.24890249734856 5.153048980215999 0.8245414537415205
NED13
['n19w156', 'n20w155', 'n20w156', 'n20w157', 'n21w156', 'n21w157', 'n21w158']
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating initial raster file
Converting to WGS84
Converting to pixel as point
Translating raster file to UTM coordinates
Snapping file to grid at 30 meters
New coordinates: 359280.000000 76350.000000 2288460.000000 2069790.000000
gdal_translate -ot Int16 temp_dem NED13
Input file size is 9431, 7289
0...10...20...30...40...50...60...70...80...90...100 - done.

Apply-Orbit-File
gpt Apply-Orbit-File -Ssource=S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip -t Apply-Orbit-File
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip: error in opening zip file
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip: error in opening zip file
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip: error in opening zip file
org.esa.snap.core.gpf.OperatorException: No product reader found for '/work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip'
        at org.esa.snap.core.gpf.main.DefaultCommandLineContext.readProduct(DefaultCommandLineContext.java:57)
        at org.esa.snap.core.gpf.main.CommandLineTool.readProduct(CommandLineTool.java:521)
        at org.esa.snap.core.gpf.main.CommandLineTool.addProduct(CommandLineTool.java:466)
        at org.esa.snap.core.gpf.main.CommandLineTool.getSourceProductMap(CommandLineTool.java:454)
        at org.esa.snap.core.gpf.main.CommandLineTool.runOperator(CommandLineTool.java:295)
        at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:284)
        at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
        at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
        at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
        at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.esa.snap.runtime.Launcher.lambda$run$14(Launcher.java:55)
        at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
        at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
        at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

Error: No product reader found for '/work/S1B_IW_GRDH_1SDV_20190430T161529_20190430T161554_016038_01E295_771B.zip'
`

**Comment by asjohnston-asf** [comment]
We occasionally see transient failures during the Apply-Orbit-File step if your computer can't connect to ESA to download the required orbit files.  Have you tried running the process again to verify this error repeats itself?

**Comment by mirzawaqar** [comment]
I am getting the same error, "No product reader found". I have already tried to run this process multiple times. Here is the complete text. 

Downloading granule from https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip

Preparing digital elevation model
Snapping to grid at posting of 30 meters
Total ned13 0 6.24413717680099 0.0
Total srtmgl1 6.247538330573946 6.24413717680099 1.0005446955562718
SRTMGL1
['N34E074', 'N34E075', 'N34E076', 'N34E077', 'N35E074', 'N35E075', 'N35E076', 'N35E077', 'N36E074', 'N36E075', 'N36E076', 'N36E077']
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating initial raster file
Translating raster file to UTM coordinates
Snapping file to grid at 30 meters
New coordinates: 699780.000000 415410.000000 4039590.000000 3813660.000000
gdal_translate -ot Int16 temp_dem SRTMGL1
Input file size is 9479, 7531
0...10...20...30...40...50...60...70...80...90...100 - done.

Apply-Orbit-File
gpt Apply-Orbit-File -Ssource=S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip -t Apply-Orbit-File
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip: error in opening zip file
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip: error in opening zip file
WARNING: org.esa.snap.engine_utilities.util.ZipUtils: unable to read zip file /work/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip: error in opening zip file
org.esa.snap.core.gpf.OperatorException: No product reader found for '/work/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip'
	at org.esa.snap.core.gpf.main.DefaultCommandLineContext.readProduct(DefaultCommandLineContext.java:57)
	at org.esa.snap.core.gpf.main.CommandLineTool.readProduct(CommandLineTool.java:521)
	at org.esa.snap.core.gpf.main.CommandLineTool.addProduct(CommandLineTool.java:466)
	at org.esa.snap.core.gpf.main.CommandLineTool.getSourceProductMap(CommandLineTool.java:454)
	at org.esa.snap.core.gpf.main.CommandLineTool.runOperator(CommandLineTool.java:295)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:284)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
	at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
	at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.esa.snap.runtime.Launcher.lambda$run$14(Launcher.java:55)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

Error: No product reader found for '/work/S1A_IW_SLC__1SDV_20171003T125656_20171003T125723_018649_01F72B_5CE3.zip'
